package fr.esgi.User_Task.domain.ports;

import com.fasterxml.jackson.annotation.JsonProperty;
import fr.esgi.User_Task.infrastructure.entity.UtilisateurEntity;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@Table(name = "taches")
public class Tache {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String titre;
    private String description;
    @JsonProperty("isDone")
    private boolean isDone;
    private LocalDate dateDebut;
    private LocalDate dateFin;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "utilisateur_id")
    @JsonProperty("utilisateurId")
    private UtilisateurEntity utilisateur;

    // Getters and setters are generated by Lombok's @Data, @Getter, and @Setter annotations
}
