-- -- PostgreSQL script
--
-- -- Database: crud
-- -- DROP DATABASE IF EXISTS crud;
-- -- CREATE DATABASE crud;
--
-- -- Connect to the database
-- -- \c crud
--
-- -- Table structure for table produit
-- CREATE TABLE tache (
--   id SERIAL PRIMARY KEY,
--   titre VARCHAR(16) NOT NULL,
--   description VARCHAR(256) DEFAULT NULL,
--   isDone BOOLEAN NOT NULL
--   dateDebut DATE NOT NULL,
--   dateFin DATE NOT NULL,
--   id_utilisateur INTEGER NOT NULL,
--   FOREIGN KEY (id_utilisateur) REFERENCES utilisateur(id)
-- );a
--
-- -- Table structure for table utilisateur
-- CREATE TABLE utilisateur (
--   id SERIAL PRIMARY KEY,
--   username VARCHAR(16) NOT NULL,
--   mail VARCHAR(32) NOT NULL,
--   password VARCHAR(32) NOT NULL,
--   role VARCHAR(16) NOT NULL
-- );